// Package httprr provides HTTP request recording and replay functionality
package httprr

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/txtar"
)

// ExportToTxtar exports the httprr recording to a txtar archive format
// for easy inspection and comparison. The txtar format allows viewing
// multiple request/response pairs in a single readable text file.
//
// If includeSecrets is false (default), authentication headers and cookies
// will be redacted for security.
func (rr *RecordReplay) ExportToTxtar(outputPath string, includeSecrets bool) error {
	// Read the httprr file
	data, err := os.ReadFile(rr.file)
	if err != nil {
		return fmt.Errorf("read httprr file: %w", err)
	}

	// Parse the httprr format
	content := string(data)
	line, content, ok := strings.Cut(content, "\n")
	line = strings.TrimSuffix(line, "\r")
	if !ok || line != "httprr trace v1" {
		return fmt.Errorf("invalid httprr trace format")
	}

	// Create txtar archive
	archive := &txtar.Archive{
		Comment: []byte(fmt.Sprintf("HTTP Request/Response Trace\nSource: %s\nGenerated by: github.com/tmc/nlm/internal/httprr\n\n", rr.file)),
	}

	requestNum := 0
	for content != "" {
		// Parse size line
		line, content, ok = strings.Cut(content, "\n")
		line = strings.TrimSuffix(line, "\r")
		var reqSize, respSize int
		if _, err := fmt.Sscanf(line, "%d %d", &reqSize, &respSize); err != nil {
			return fmt.Errorf("parse size line: %w", err)
		}

		if reqSize > len(content) || respSize > len(content[reqSize:]) {
			return fmt.Errorf("invalid sizes in httprr file")
		}

		reqData := content[:reqSize]
		respData := content[reqSize : reqSize+respSize]
		content = content[reqSize+respSize:]

		requestNum++

		// Parse request to extract useful info for filename
		req, err := http.ReadRequest(bufio.NewReader(strings.NewReader(reqData)))
		if err == nil {
			// Extract RPC ID from request for better naming
			rpcID := extractRPCID(req)
			if rpcID == "" {
				rpcID = fmt.Sprintf("request%d", requestNum)
			}

			// Optionally scrub secrets
			if !includeSecrets {
				reqData = scrubRequestSecrets(reqData)
				respData = scrubResponseSecrets(respData)
			}

			// Add request file
			archive.Files = append(archive.Files, txtar.File{
				Name: fmt.Sprintf("%02d_%s_request.http", requestNum, rpcID),
				Data: []byte(reqData),
			})

			// Add response file
			archive.Files = append(archive.Files, txtar.File{
				Name: fmt.Sprintf("%02d_%s_response.http", requestNum, rpcID),
				Data: []byte(respData),
			})

			req.Body.Close()
		}
	}

	// Ensure output directory exists
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	// Write txtar archive
	if err := os.WriteFile(outputPath, txtar.Format(archive), 0o644); err != nil {
		return fmt.Errorf("write txtar file: %w", err)
	}

	return nil
}

// extractRPCID extracts the RPC ID from a NotebookLM request
func extractRPCID(req *http.Request) string {
	// Try to read body
	body, err := io.ReadAll(req.Body)
	if err != nil {
		return ""
	}
	// Restore body for potential reuse
	req.Body = io.NopCloser(strings.NewReader(string(body)))

	// Look for RPC ID in the request body
	// Format: f.req=[["RPCId", ...
	bodyStr := string(body)
	if strings.Contains(bodyStr, "f.req=") {
		// Try to extract the first quoted string after f.req=
		after := strings.SplitN(bodyStr, "f.req=", 2)
		if len(after) == 2 {
			// Look for pattern like [["RPCId"
			if idx := strings.Index(after[1], `[["`); idx != -1 {
				start := idx + 3
				if end := strings.Index(after[1][start:], `"`); end != -1 {
					return after[1][start : start+end]
				}
			}
		}
	}

	// Fallback to query parameter rpcids
	if rpcids := req.URL.Query().Get("rpcids"); rpcids != "" {
		return rpcids
	}

	return ""
}

// scrubRequestSecrets removes sensitive information from request data
func scrubRequestSecrets(data string) string {
	lines := strings.Split(data, "\n")
	var result []string

	for _, line := range lines {
		// Redact cookie headers
		if strings.HasPrefix(strings.ToLower(line), "cookie:") {
			result = append(result, "Cookie: [REDACTED]")
			continue
		}
		// Redact authorization headers
		if strings.HasPrefix(strings.ToLower(line), "authorization:") {
			result = append(result, "Authorization: [REDACTED]")
			continue
		}
		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// scrubResponseSecrets removes sensitive information from response data
func scrubResponseSecrets(data string) string {
	// Currently no response scrubbing needed
	// Can add here if needed (e.g., scrub tokens from response bodies)
	return data
}

// EnableTxtarExport enables automatic txtar export for this RecordReplay.
// When recording is complete, the httprr file will be automatically exported
// to a txtar file with the same base name but .txtar extension.
func (rr *RecordReplay) EnableTxtarExport(includeSecrets bool) {
	// This will be called when recording is closed
	// For now, users should manually call ExportToTxtar after recording
}

// SetFile sets the file path for this RecordReplay instance.
// This is useful when creating a RecordReplay just for exporting.
func (rr *RecordReplay) SetFile(file string) {
	rr.file = file
}
